# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vivado_pj/masterDesign/masterDesign.srcs/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz.xci
# IP: The module: 'clock_gen_24MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/vivado_pj/masterDesign/masterDesign.srcs/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz.xci
# IP: The module: 'clock_gen_24MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clock_gen_24MHz/clock_gen_24MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_gen_24MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
