# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vivado_pj/masterDesign/masterDesign.srcs/sources_1/ip/clk_gen_100/clk_gen_100.xci
# IP: The module: 'clk_gen_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/vivado_pj/masterDesign/masterDesign.srcs/sources_1/ip/clk_gen_100/clk_gen_100.xci
# IP: The module: 'clk_gen_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/vivado_pj/masterDesign/masterDesign.gen/sources_1/ip/clk_gen_100/clk_gen_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_gen_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
